exclude: 'build|stubs'

default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: end-of-file-fixer

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
